executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: file_name
    json_schema:
      type: string
  - handle: data_rows
    json_schema:
      type: array
outputs_def:
  - handle: summary
    json_schema:
      type: string
  - handle: fields_schema
    json_schema:
      type: array
title: " Summarize data"
description: |-
  使用 ai 分析用户输入的文件数据，生成总结和数据结构

  file_path: 需要处理的文件路径
  data_summary： 生成的文件总结
  fields: 从文件中提取的字段
icon: ":carbon:report:"
