description: Generate comprehensive summary statistics and data insights for
  tabular datasets
executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: file_name
    json_schema:
      type: string
  - handle: data_rows
    json_schema:
      type: array
outputs_def:
  - handle: summary
    json_schema:
      type: string
  - handle: fields_schema
    json_schema:
      type: array
title: " Summarize data"
icon: ":carbon:report:"
private: true
