ui:
  default_width: 450
inputs_def:
  - handle: data
    json_schema:
      type: array
  - handle: x_column
    description: Input
    json_schema:
      type: string
    value:
    nullable: true
  - handle: y_column
    json_schema:
      type: string
    value:
    nullable: true
outputs_def:
  []
executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
title: Result Chart
description: 结果表格
icon: ":carbon:chart-average:"
