ui:
  default_width: 450
inputs_def:
  - handle: data
    json_schema:
      type: array
  - handle: title
    json_schema:
      type: string
    value:
    nullable: true
  - handle: x_column
    description: 横轴列名
    json_schema:
      type: string
    value:
    nullable: true
  - handle: y_column
    description: 纵轴列名
    json_schema:
      type: string
    value:
    nullable: true
  - handle: chart_type
    description: 图表类型，留空自动选择
    json_schema:
      type: string
      enum:
        - bar
        - line
        - scatter
        - pie
        - histogram
        - box
        - area
        - radar
        - heatmap
        - violin
        - bubble
    value: pie
outputs_def:
  - handle: status
    json_schema:
      type: string
  - handle: chart_type
    json_schema:
      type: string
  - handle: columns_used
    json_schema:
      type: array
  - handle: data_points
    json_schema:
      type: number
executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
title: Result Chart
description: 结果表格
icon: ":carbon:chart-average:"
private: true
