ui:
  default_width: 450
inputs_def:
  - handle: data
    json_schema:
      type: array
  - handle: title
    json_schema:
      type: string
    value:
    nullable: true
  - handle: x_column
    description: Column name for the x-axis
    json_schema:
      type: string
    value:
    nullable: true
  - handle: y_column
    description: Column name for the y-axis
    json_schema:
      type: string
    value:
    nullable: true
  - handle: chart_type
    description: Chart type, leave empty for auto selection
    json_schema:
      type: string
      enum:
        - bar
        - line
        - scatter
        - pie
        - histogram
        - box
        - area
        - radar
        - heatmap
        - violin
        - bubble
    value: pie
outputs_def:
  - handle: status
    json_schema:
      type: string
  - handle: chart_type
    json_schema:
      type: string
  - handle: columns_used
    json_schema:
      type: array
  - handle: data_points
    json_schema:
      type: number
executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
title: Chart Preview
description: Create interactive charts and visualizations from processed data
  with customizable axes and titles. Note, Users may use this block not only to
  get return results, but also to view and examine the generated charts.
icon: ":carbon:chart-average:"
private: false
