executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: data
    json_schema:
      type: array
      items:
        type: object
        additionalProperties: false
        properties:
          name:
            type: string
          rows:
            type: array
    value:
      []
  - handle: instruction
    json_schema:
      type: string
      ui:widget: text
  - group: Group
  - handle: x_axis_name
    json_schema:
      type: string
    value:
    nullable: true
  - handle: y_axis_name
    json_schema:
      type: string
    value:
    nullable: true
  - handle: code_repair_attempts
    json_schema:
      type: integer
    nullable: true
  - handle: llm_model
    json_schema:
      ui:options:
        title: Model
      ui:widget: llm::model
    value:
      model: openai/gpt-4.1
      temperature: 0
      top_p: 0.5
      max_tokens: 4096
outputs_def:
  - handle: code_for_derive
    json_schema:
      type: string
  - handle: code_explain
    json_schema:
      type: string
  - handle: content
    json_schema:
      type: array
  - handle: refined_x_axis_name
    json_schema:
      type: string
  - handle: refined_y_axis_name
    json_schema:
      type: string
title: Derive data
description: Transform and derive new data insights from existing datasets using
  AI-powered analysis and custom calculations
icon: ":carbon:ibm-application-and-discovery-delivery-intelligence:"
additional_inputs: false
private: true
