executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: data
    description: "Input dataset containing tables with name and rows structure"
    json_schema:
      type: array
      items:
        type: object
        additionalProperties: false
        properties:
          name:
            type: string
          rows:
            type: array
    value:
      []
  - handle: instruction
    description: "Natural language instruction describing the data transformation or
      analysis to perform"
    json_schema:
      type: string
      ui:widget: textarea
      ui:options:
        rows: 4
        placeholder: "Describe what analysis or transformation you want to perform on
          the data..."
  - group: Group
  - handle: x_axis_name
    description: "Optional name for the X-axis field in visualization"
    json_schema:
      type: string
    value: null
    nullable: true
  - handle: y_axis_name
    description: "Optional name for the Y-axis field in visualization"
    json_schema:
      type: string
    value: null
    nullable: true
  - handle: code_repair_attempts
    description: "Maximum number of attempts to repair generated code if errors
      occur (default: 3)"
    json_schema:
      type: integer
      minimum: 1
      maximum: 10
    value: 3
    nullable: true
  - handle: llm_model
    description: "LLM model configuration for data transformation agent"
    json_schema:
      ui:options:
        title: Model
      ui:widget: llm::model
    value:
      model: openai/gpt-4.1
      temperature: 0
      top_p: 0.5
      max_tokens: 4096
outputs_def:
  - handle: code_for_derive
    description: "Generated Python code that performs the data transformation"
    json_schema:
      type: string
  - handle: code_explain
    description: "Human-readable explanation of what the generated code does"
    json_schema:
      type: string
  - handle: analysis_logic
    description: "Analysis logic and processing thoughts in markdown format"
    json_schema:
      type: string
  - handle: content
    description: "Transformed data result as an array of objects"
    json_schema:
      type: array
      items:
        type: object
  - handle: refined_x_axis_name
    description: "Final determined name for X-axis field"
    json_schema:
      type: string
  - handle: refined_y_axis_name
    description: "Final determined name for Y-axis field"
    json_schema:
      type: string
title: Derive data
description: Transform and derive new data insights from existing datasets using
  AI-powered analysis and custom calculations
icon: ":carbon:ibm-application-and-discovery-delivery-intelligence:"
additional_inputs: false
private: true
