ui:
  default_width: 450
inputs_def:
  - handle: tables
    description: Input
    json_schema:
      type: array
      items:
        type: string
        ui:widget: file
  - handle: enable_preview
    json_schema:
      type: boolean
    value: true
outputs_def:
  - handle: output
    description: Output
    json_schema:
      type: array
      items:
        type: object
        additionalProperties: false
        properties:
          name:
            type: string
          rows:
            type: array
executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
title: Read Files
description: Read and preview CSV or Excel files from local storage with
  optional data preview functionality. Note, Users may use this block not only
  to get return results, but also to view and examine the original file content.
private: true
icon: ":carbon:port-input:"
